work_dir: /home/magnus/pb-gcn/centernet4hz/cs
data_path: /home/jaagaard/magnus_od/action_recognition/datasets/NTURGBD/skeleton
missing_txt: /home/magnus/pb-gcn/samples_with_missing_skeletons.txt

# Data Loader
loader: NTULoader
test_loader_args:
  split_dir: /home/magnus/pb-gcn/datasets/cs
  is_training: False
  is_test: True
  signals:
    temporal_signal: True
    spatial_signal: True
    all_signal: False

# Model
model: ST_GCONV_RESNET
model_args:
  layers_config: [[64, 64, 1], [64, 64, 1], [64, 64, 1], [64, 128, 2], [128, 128, 1],
      [128, 128, 1], [128, 256, 2], [256, 256, 1], [256, 256, 1]]
  num_class: 60
  channel: 15
  window_size: 25
  num_joints: 17
  num_actors: 2
  graph: CenterNetGraph
  graph_args:
    labeling_mode: 'parts'
  mask_learning: True
  use_data_bn: True

# Eval
device: [0]
test_batch_size: 64
phase: test

# Initialization from checkpoint
weights: ./centernet4hz/cs/epoch10_model.pt
