work_dir: /ssd_scratch/cvit/kalpit.t/stgcn/work_dir/NTURGBD/xsub/ST_GCN_parts_noaug

# loader
loader: NTULoader
train_loader_args:
  split_dir: /ssd_scratch/cvit/kalpit.t/stgcn/data/xsub
  signals:
    temporal_signal: False
    spatial_signal: False
    all_signal: False
  #transforms: ['RandomAffineTransformAcrossTime']
  #transform_args:
  #  angle_choices: [-10., -5., 0, 5., 10.]
  #  scale_choices: [0.9, 1.0, 1.1]
  #  translate_choices: [-0.2, -0.1, 0.0, 0.1, 0.2]
  #  tsmoothness_choices: [1]
test_loader_args:
  split_dir: /ssd_scratch/cvit/kalpit.t/stgcn/data/xsub
  is_training: False
  signals:
    temporal_signal: False
    spatial_signal: False
    all_signal: False

# model
model: ST_GCONV_RESNET
model_args:
  layers_config: [[64, 64, 1], [64, 64, 1], [64, 64, 1], [64, 128, 2], [128, 128, 1], 
      [128, 128, 1], [128, 256, 2], [256, 256, 1], [256, 256, 1]]
  num_class: 60
  channel: 3
  window_size: 300
  num_joints: 25
  num_actors: 2
  graph: NTUGraph
  graph_args:
    labeling_mode: 'parts'
  mask_learning: True
  use_data_bn: True

# optim
weight_decay: 0.0001
base_lr: 0.1
step: [20, 50, 70]

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 64
num_epoch: 80
nesterov: True
save_interval: 5

# eval
eval_interval: 5

# initialize
# start_epoch: 50
# weights: /ssd_scratch/cvit/kalpit.t/stgcn/work_dir/NTURGBD/xsub/ST_GCN_oldlabel_combined_signals/epoch50_model.pt
